[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
first_try = "5g4ZntfHahpwUHvdGcKiBfQLjqzC9T8CY44GBTp8xygU"
ownable-like = "4Zj5nmy5UxjE5VJ119PxYCcj9EEvhst6G98QCsAcmXQJ"
second-try = "9vXeG29pgE2FGtRWSv1XLBuqR6pXY565a5kXr86HEDrE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
